#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) exit;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Unpack Super"
    echo "2. Convert dat.br to raw img"
    echo "3. Mount raw .img"
    echo "4. Convert raw to sparse"
    echo "5. Unpack payload.bin"
    echo "6. Unmount images"
    echo "7. Repack Super"
    echo "8. Convert raw .img to dat.br"
    echo "9. Compress split partitons (raw to dat.br)"
    echo "10. Auto ZIP"
    echo "11. Clean up folders"
    echo "12. Exit tool"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/super-u

restart_tool;;

        2 ) 
   
bash $SCRIPTS/unpack

restart_tool;;

        3 ) 
        
bash $SCRIPTS/mount
        
restart_tool;;

        4 ) 
        
bash $SCRIPTS/raw-sparse
        
restart_tool;;

        5 ) 
        
bash $SCRIPTS/payload
        
restart_tool;;

        6 ) 
        
bash $SCRIPTS/umount
        
restart_tool;;

        7 ) 
        
bash $SCRIPTS/super-r
        
restart_tool;;

        8 ) 
        
bash $SCRIPTS/repack
        
restart_tool;;

        9 ) 
        
bash $SCRIPTS/compress-splits
        
restart_tool;;

        10 ) 
        
bash $SCRIPTS/zip-main
        
restart_tool;;

        11 ) 
        
bash $SCRIPTS/clean
        
restart_tool;;

        12 )  exit;;


        * ) bash start;;
    esac
done


