#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts
bash $SCRIPTS/setup
clear
cd $DIRTOOLS
rm -rf $SCRIPTS/log.txt

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) exit;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Super partition tools"
    echo "2. Split partition tools (system,vendor,odm,system_ext,product)"
    echo "3. Convert dat.br to raw img"
    echo "4. Convert raw .img to dat.br"
    echo "5. Convert raw to sparse"
    echo "6. Convert sparse to raw"
    echo "7. Mount raw .img"
    echo "8. Unmount images"
    echo "9. Unpack payload.bin"
    echo "10. Merge fs context and config to system"
    echo "11. Convert erofs to ext4"
    echo "12. Auto ZIP"
    echo "13. idk... port oplus? build oplus? convert oplus?"
    echo "14. Clean up folders"
    echo "15. Exit tool"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/super-main

restart_tool;;

        2 ) 
   
bash $SCRIPTS/splits-main

restart_tool;;

        3 ) 
        
bash $SCRIPTS/datbr-raw
        
restart_tool;;

        4 ) 
        
bash $SCRIPTS/raw-datbr
        
restart_tool;;

        5 ) 
        
bash $SCRIPTS/raw-sparse
        
restart_tool;;

        6 ) 
        
bash $SCRIPTS/sparse-raw
        
restart_tool;;

        7 ) 
        
bash $SCRIPTS/mount-main
        
restart_tool;;

        8 ) 
        
bash $SCRIPTS/umount-main
        
restart_tool;;

        9 ) 
        
bash $SCRIPTS/payload
        
restart_tool;;

        10 ) 
        
bash $SCRIPTS/merge-main
        
restart_tool;;

        11 ) 
        
bash $SCRIPTS/erofs-ext4-main
        
restart_tool;;

        12 ) 
        
bash $SCRIPTS/zip-main
        
restart_tool;;

        13 ) 
        
bash $SCRIPTS/oplus-script
        
restart_tool;;

        14 ) 
        
bash $SCRIPTS/clean
        
restart_tool;;

        15 )  exit;;


        * ) bash start;;
    esac
done


