#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) break;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Unpack Super"
    echo "2. Convert dat.br to raw img"
    echo "3. Mount raw .img"
    echo "4. Convert raw to sparse"
    echo "5. Unpack payload.bin"
    echo "6. Unmount images"
    echo "7. Repack Super"
    echo "8. Convert raw .img to dat.br"
    echo "9. Compress split partitons (raw to dat.br)"
    echo "C. Clean up folders"
    
    read -p "" choose
    case $choose in
        1 ) 

bash $SCRIPTS/super-u

restart_tool
break;;

        2 ) 
   
bash $SCRIPTS/unpack

restart_tool
break;;

        3 ) 
        
bash $SCRIPTS/mount
        
restart_tool
break;;


        4 ) 
        
bash $SCRIPTS/raw-sparse
        
restart_tool
break;;

        5 ) 
        
bash $SCRIPTS/payload
        
restart_tool
break;;

        6 ) 
        
bash $SCRIPTS/umount
        
restart_tool
break;;

        7 ) 
        
bash $SCRIPTS/super-r
        
restart_tool
break;;

        8 ) 
        
bash $SCRIPTS/repack
        
restart_tool
break;;

        9 ) 
        
bash $SCRIPTS/compress-splits
        
restart_tool
break;;

        10 ) 
        
bash $SCRIPTS/clean
        
restart_tool
break;;


        * ) bash start;;
    esac
done


