#!/bin/bash

COMPLVL=9

USER=danda
DIRTOOLS=/home/$USER/Desktop
DIRIN=$DIRTOOLS/RomTools/brotli/input
DIROUT=$DIRTOOLS/RomTools/brotli/output

brotli -q $COMPLVL $DIRIN/system.new.dat --output=$DIROUT/system.new.dat.br
brotli -q $COMPLVL $DIRIN/vendor.new.dat --output=$DIROUT/vendor.new.dat.br
brotli -q $COMPLVL $DIRIN/odm.new.dat --output=$DIROUT/odm.new.dat.br
brotli -q $COMPLVL $DIRIN/product.new.dat --output=$DIROUT/product.new.dat.br
brotli -q $COMPLVL $DIRIN/system_ext.new.dat --output=$DIROUT/system_ext.new.dat.br
brotli -q $COMPLVL $DIRIN/oxygen.new.dat --output=$DIROUT/oxygen.new.dat.br
brotli -q $COMPLVL $DIRIN/oneplus.new.dat --output=$DIROUT/oneplus.new.dat.br
brotli -q $COMPLVL $DIRIN/miui.new.dat --output=$DIROUT/miui.new.dat.br
brotli -q $COMPLVL $DIRIN/myui.new.dat --output=$DIROUT/myui.new.dat.br
brotli -q $COMPLVL $DIRIN/super.new.dat --output=$DIROUT/super.new.dat.br

rm -rf $DIRIN/*
