#!/bin/bash

USER=danda
DIRTOOLS=/home/$USER/Desktop
DIRIN=$DIRTOOLS/RomTools/brotli/input
DIROUT=$DIRTOOLS/RomTools/brotli/output

brotli -d $DIRIN/system.new.dat.br --output=$DIROUT/system.new.dat
brotli -d $DIRIN/vendor.new.dat.br --output=$DIROUT/vendor.new.dat
brotli -d $DIRIN/odm.new.dat.br --output=$DIROUT/odm.new.dat
brotli -d $DIRIN/product.new.dat --output=$DIROUT/product.new.dat.br
brotli -d $DIRIN/system_ext.new.dat.br --output=$DIROUT/system_ext.new.dat
brotli -d $DIRIN/oxygen.new.dat.br --output=$DIROUT/oxygen.new.dat
brotli -d $DIRIN/oneplus.new.dat.br --output=$DIROUT/oneplus.new.dat
brotli -d $DIRIN/miui.new.dat.br --output=$DIROUT/miui.new.dat
brotli -d $DIRIN/myui.new.dat.br --output=$DIROUT/myui.new.dat
brotli -d $DIRIN/super.new.dat.br --output=$DIROUT/super.new.dat



rm -rf $DIRIN/*
