#!/bin/bash
DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
DIRSCRIPTS=$DIRTOOLS/scripts
clear

convert() {
	mkdir $DIRIN/tmp
	echo "==========================="
	echo ""
	echo "Unpacking $apex..."
	unzip $DIRIN/$apex -d $DIRIN/tmp/
	echo ""
	echo "Mounting apex_payload.img..."
	mkdir $DIRIN/tmp/mount
	sudo mount -t ext4 -o ro,nosuid,nodev,relatime,seclabel,errors=remount-ro,uhelper=udisks2 $DIRIN/tmp/apex_payload.img $DIRIN/tmp/mount
	apexfolder=$(echo $apex | awk '{ print substr( $0, 1, length($0)-5 ) }' )
	mkdir $DIROUT/$apexfolder
	echo ""
	echo "Copying important files"
	cp $DIRIN/tmp/apex_pubkey $DIROUT/$apexfolder/
	sudo cp -r $DIRIN/tmp/mount/* $DIROUT/$apexfolder/
	sudo chown -R $USER $DIROUT/$apexfolder/*
	echo ""
	echo "Cleaning..."
	echo ""
	sudo umount $DIRIN/tmp/mount
	rm -rf $DIRIN/tmp
	rm -rf $DIRIN/$apex
}

apex=com.android.apex.cts.shim.apex
convert
apex=com.android.i18n.apex
convert
apex=com.android.runtime.apex
convert
apex=com.android.uwb.apex
convert
apex=com.android.vndk.current.apex
convert
apex=com.android.wifi.apex
convert
apex=com.google.android.adbd_trimmed.apex
convert
apex=com.google.android.adservices.apex
convert
apex=com.google.android.appsearch.apex
convert
apex=com.google.android.art.apex
convert
apex=com.google.android.cellbroadcast.apex
convert
apex=com.google.android.conscrypt.apex
convert
apex=com.google.android.extservices.apex
convert
apex=com.google.android.ipsec.apex
convert
apex=com.google.android.media.apex
convert
apex=com.google.android.media.swcodec.apex
convert
apex=com.google.android.mediaprovider.apex
convert
apex=com.google.android.neuralnetworks.apex
convert
apex=com.google.android.ondevicepersonalization.apex
convert
apex=com.google.android.os.statsd.apex
convert
apex=com.google.android.permission.apex
convert
apex=com.google.android.resolv.apex
convert
apex=com.google.android.scheduling.apex
convert
apex=com.google.android.sdkext.apex
convert
apex=com.google.android.tethering.apex
convert
apex=com.google.android.tzdata4.apex
convert
apex=com.google.mainline.primary.libs.apex
convert

cd $DIROUT/
zip -r $DIRIN/non-updatable.apex.zip *
cd ..
rm -rf $DIROUT/*
mv $DIRIN/non-updatable.apex.zip $DIROUT/
