#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
DIRROM=$DIRTOOLS/ROM
clear

echo "cleaning..."

rm -rf $DIRIN/*
rm -rf $DIROUT/*
rm -rf $DIRROM/*
rm -rf $DIRTOOLS/scripts/log.txt

echo "Done!"
