#!/bin/bash

DIRTOOLS=$PWD
DIRROM=$DIRTOOLS/ROM

sudo chown -R $USER:$USER $DIRROM/system
sudo chown -R $USER:$USER $DIRROM/vendor
sudo chown -R $USER:$USER $DIRROM/odm
sudo chown -R $USER:$USER $DIRROM/system_ext
sudo chown -R $USER:$USER $DIRROM/product
