#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) exit;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Merge OPLUS my_* partition to system"
    echo "2. Merge product and system_ext to system"
    echo "3. Back to main menu"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/merge-oplus

restart_tool;;

        2 ) 

bash $SCRIPTS/merge-non-dynamic

restart_tool;;

        3 ) 

bash $DIRTOOLS/start;;


        * ) bash $SCRIPTS/umount-main;;
    esac
done


