#!/bin/sh

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
OPLUSMERGE=$DIRTOOLS/scripts/oplus
clear

if [[ -f $DIRIN/system_file_contexts ]] && [[ -f $DIRIN/system_fs_config ]]; then
   merge() {
     if [[ -f $DIRIN/${partition}_file_contexts ]] && [[ -f $DIRIN/${partition}_fs_config ]]; then
     	echo ""
     	echo "Merging $partition fs config & file contexts to system"
     	echo ""
	gawk -i inplace 'NR>1' $DIRIN/${partition}_file_contexts

	python3 $OPLUSMERGE/$partition.py $DIRIN/${partition}_file_contexts
	python3 $OPLUSMERGE/$partition.py $DIRIN/${partition}_fs_config

	cat $DIRIN/${partition}_file_contexts >> $DIRIN/system_file_contexts
	cat $DIRIN/${partition}_fs_config >> $DIRIN/system_fs_config
     else
     	echo ""
     	echo "There's no $partition file contexts and/or fs config supplied"
     	echo ""
     fi
   }
   
   partition=my_bigball
   merge
   partition=my_carrier
   merge
   partition=my_company
   merge
   partition=my_engineering
   merge
   partition=my_heytap
   merge
   partition=my_manifest
   merge
   partition=my_preload
   merge
   partition=my_product
   merge
   partition=my_region
   merge
   partition=my_stock
   merge

   rm -rf $DIRIN/my_*
   mv $DIRIN/system_file_contexts $DIROUT/
   mv $DIRIN/system_fs_config $DIROUT/
	
echo "merged all fs context and config.. Output : $DIROUT"

else
	echo "Error : put your system_file_contexts & system_fs_config to $DIRIN"
	
fi

