#!/bin/bash

DIRTOOLS=$PWD
DIRROM=$DIRTOOLS/ROM
GIVEPERM=$DIRTOOLS/scripts/give_perm
clear
cd scripts

resize_img_to_edit(){
		getsize=$(ls -nl $DIRROM/$valset.img | awk '{print $5}')
		readgiga=$(($getsize / 1000000000))
		sizeimg=$(($readgiga + 1))G
		fallocate -l $sizeimg $DIRROM/$valset.img
		e2fsck -yf $DIRROM/$valset.img
		resize2fs $DIRROM/$valset.img $sizeimg
		e2fsck -yf $DIRROM/$valset.img
}

# Resize image before mount
valset=system
resize_img_to_edit;
valset=system_ext
resize_img_to_edit;
valset=vendor
resize_img_to_edit;
valset=product
resize_img_to_edit;
valset=odm
resize_img_to_edit;


valset=system_a
resize_img_to_edit;
valset=system_ext_a
resize_img_to_edit;
valset=vendor_a
resize_img_to_edit;
valset=product_a
resize_img_to_edit;
valset=odm_a
resize_img_to_edit;

sudo mount -t ext4 -o loop $DIRROM/system.img $DIRROM/system
sudo mount -t ext4 -o loop $DIRROM/vendor.img $DIRROM/vendor
sudo mount -t ext4 -o loop $DIRROM/odm.img $DIRROM/odm
sudo mount -t ext4 -o loop $DIRROM/product.img $DIRROM/product
sudo mount -t ext4 -o loop $DIRROM/system_ext.img $DIRROM/system_ext

sudo mount -t ext4 -o loop $DIRROM/system_a.img $DIRROM/system
sudo mount -t ext4 -o loop $DIRROM/vendor_a.img $DIRROM/vendor
sudo mount -t ext4 -o loop $DIRROM/odm_a.img $DIRROM/odm
sudo mount -t ext4 -o loop $DIRROM/product_a.img $DIRROM/product
sudo mount -t ext4 -o loop $DIRROM/system_ext_a.img $DIRROM/system_ext

bash give_perm
