#!/bin/bash

DIRTOOLS=$PWD
DIRROM=$DIRTOOLS/ROM
GIVEPERM=$DIRTOOLS/scripts/give_perm
OPTIONS=loop
clear
cd scripts

resize_img_to_edit(){
		getsize=$(ls -nl $DIRROM/$valset.img | awk '{print $5}')
		readmb=$(($getsize / 100000000))
		readgiga=$(($getsize / 1000000000))
		cval=$(($readmb - $readgiga))
		if [[ $cval -gt 5 ]]; then
			vplus=2;
		else
			vplus=1;
		fi
		sizeimg=$(($readgiga + $vplus))G
		fallocate -l $sizeimg $DIRROM/$valset.img  >> log.txt
		e2fsck -yf $DIRROM/$valset.img  >> log.txt
		resize2fs $DIRROM/$valset.img $sizeimg  >> log.txt
		e2fsck -yf $DIRROM/$valset.img  >> log.txt
}

echo " "
echo "Resizing partitions..."
echo " "
valset=system
resize_img_to_edit
valset=system_ext
resize_img_to_edit
valset=vendor
resize_img_to_edit
valset=product
resize_img_to_edit
valset=odm
resize_img_to_edit

valset=system_a
resize_img_to_edit
valset=system_ext_a
resize_img_to_edit
valset=vendor_a
resize_img_to_edit
valset=product_a
resize_img_to_edit
valset=odm_a
resize_img_to_edit

echo " "
echo "Mounting partitions..."
echo " "
if [[ -f $DIRROM/system_a.img ]] || [[ -f $DIRROM/vendor_a.img ]] || [[ -f $DIRROM/odm_a.img ]] || [[ -f $DIRROM/product_a.img ]] || [[ -f $DIRROM/system_ext_a.img ]]; then

	sudo mount -t ext4 -o $OPTIONS $DIRROM/system_a.img $DIRROM/system >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/vendor_a.img $DIRROM/vendor >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/odm_a.img $DIRROM/odm >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/product_a.img $DIRROM/product >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/system_ext_a.img $DIRROM/system_ext >> log.txt

else

	sudo mount -t ext4 -o $OPTIONS $DIRROM/system.img $DIRROM/system >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/vendor.img $DIRROM/vendor >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/odm.img $DIRROM/odm >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/product.img $DIRROM/product >> log.txt
	sudo mount -t ext4 -o $OPTIONS $DIRROM/system_ext.img $DIRROM/system_ext >> log.txt

fi
bash give_perm
