#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
clear
cd scripts

echo " "
echo "Input image/partition name :"
read
imgname=$REPLY

echo " "
echo " "
echo "Input Brotli compression level (0-11) :"
read
COMPLVL=$REPLY

echo " " 
echo "converting image : $imgname to sparse"
img2simg $DIRIN/$imgname.img $DIRIN/$imgname.sparse.img >> log.txt
rm -rf $DIRIN/$imgname.img

echo " " 
echo "converting image : $imgname to new.dat"
./bin/img2sdat.py $DIRIN/$imgname.sparse.img -o $DIRIN/ -v 4 >> log.txt
rm -rf $DIRIN/$imgname.sparse.img
mv $DIRIN/system.new.dat $DIROUT/$imgname.new.dat
mv $DIRIN/system.patch.dat $DIROUT/$imgname.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/$imgname.transfer.list
rm -rf $DIRIN/system.*

echo " " 
echo "compressing image : $imgname using brotli..."

brotli -q $COMPLVL $DIROUT/$imgname.new.dat --output=$DIROUT/$imgname.new.dat.br
echo " "
echo "cleaning..."

rm -rf $DIROUT/$imgname.new.dat
echo " "
echo "Done! Output : $DIROUT"
