#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
cd scripts
clear

echo " "
echo "Input image/partition name :"
read
imgname=$REPLY

echo " "
echo "Converting raw image to sparse..."

img2simg $DIRIN/$imgname.img $DIROUT/$imgname.sparse.img >> log.txt

echo " "
echo "Done! Output : $DIROUT"

