#!/bin/bash

USER=danda
DIRTOOLS=/home/$USER/Desktop
DIRROM=$DIRTOOLS/RomTools/ROM
DIROUT=$DIRTOOLS/RomTools/rom_output

bash umount


img2simg $DIRROM/system.img $DIRROM/system.sparse.img
img2simg $DIRROM/vendor.img $DIRROM/vendor.sparse.img
img2simg $DIRROM/odm.img $DIRROM/odm.sparse.img
img2simg $DIRROM/product.img $DIRROM/product.sparse.img
img2simg $DIRROM/system_ext.img $DIRROM/system_ext.sparse.img

./bin/img2sdat.py $DIRROM/system.sparse.img -o $DIRROM/ -v 4
cp $DIRROM/system.new.dat $DIROUT/system.new.dat
cp $DIRROM/system.patch.dat $DIROUT/system.patch.dat
cp $DIRROM/system.transfer.list $DIROUT/system.transfer.list
rm -rf $DIRROM/system.*

./bin/img2sdat.py $DIRROM/vendor.sparse.img -o $DIRROM/ -v 4
cp $DIRROM/system.new.dat $DIROUT/vendor.new.dat
cp $DIRROM/system.patch.dat $DIROUT/vendor.patch.dat
cp $DIRROM/system.transfer.list $DIROUT/vendor.transfer.list
rm -rf $DIRROM/system.*
rm -rf $DIRROM/vendor.*

./bin/img2sdat.py $DIRROM/odm.sparse.img -o $DIRROM/-v 4
cp $DIRROM/system.new.dat $DIROUT/odm.new.dat
cp $DIRROM/system.patch.dat $DIROUT/odm.patch.dat
cp $DIRROM/system.transfer.list $DIROUT/odm.transfer.list
rm -rf $DIRROM/system.*
rm -rf $DIRROM/odm.*

./bin/img2sdat.py $DIRROM/product.sparse.img -o $DIRROM/ -v 4
cp $DIRROM/system.new.dat $DIROUT/product.new.dat
cp $DIRROM/system.patch.dat $DIROUT/product.patch.dat
cp $DIRROM/system.transfer.list $DIROUT/product.transfer.list
rm -rf $DIRROM/system.*
rm -rf $DIRROM/product.*

./bin/img2sdat.py $DIRROM/system_ext.sparse.img -o $DIRROM/-v 4
cp $DIRROM/system.new.dat $DIROUT/system_ext.new.dat
cp $DIRROM/system.patch.dat $DIROUT/system_ext.patch.dat
cp $DIRROM/system.transfer.list $DIROUT/system_ext.transfer.list
rm -rf $DIRROM/system.*
rm -rf $DIRROM/system_ext.*

echo " "
echo " "
echo " "
while true; do
    read -p "Do you want to compress it using brotli? (Y/N)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


echo " "
echo " "
echo "Input Brotli compression level (0-11) :"
read
COMPLVL=$REPLY
echo " "
while true; do
    read -p "Your preffered brotli compression level is $COMPLVL is that correct? (Y/N)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo " "

echo " " 
echo "compressing partitions using brotli..."

brotli -q $COMPLVL $DIROUT/system.new.dat --output=$DIROUT/system.new.dat.br
brotli -q $COMPLVL $DIROUT/vendor.new.dat --output=$DIROUT/vendor.new.dat.br
brotli -q $COMPLVL $DIROUT/odm.new.dat --output=$DIROUT/odm.new.dat.br
brotli -q $COMPLVL $DIROUT/product.new.dat --output=$DIROUT/product.new.dat.br
brotli -q $COMPLVL $DIROUT/system_ext.new.dat --output=$DIROUT/system_ext.new.dat.br

echo "cleaning..."
echo " "

rm -rf $DIROUT/system.new.dat
rm -rf $DIROUT/vendor.new.dat
rm -rf $DIROUT/odm.new.dat
rm -rf $DIROUT/product.new.dat
rm -rf $DIROUT/system_ext.new.dat

echo "compession done!";
echo " "

