#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
clear
cd scripts

echo " "
echo "Input image/partition name :"
read
imgname=$REPLY


img2simg $DIRIN/$imgname.img $DIRIN/$imgname.sparse.img

./bin/img2sdat.py $DIRIN/$imgname.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/$imgname.new.dat
mv $DIRIN/system.patch.dat $DIROUT/$imgname.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/$imgname.transfer.list
rm -rf $DIRIN/system.*
rm -rf $DIRIN/$imgname.*


echo " "
echo " "
echo " "
while true; do
    read -p "Do you want to compress it using brotli? (Y/N)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done


echo " "
echo " "
echo "Input Brotli compression level (0-11) :"
read
COMPLVL=$REPLY
echo " "
while true; do
    read -p "Your preffered brotli compression level is $COMPLVL is that correct? (Y/N)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo " "

echo " " 
echo "compressing partitions using brotli..."

brotli -q $COMPLVL $DIROUT/$imgname.new.dat --output=$DIROUT/$imgname.new.dat.br
echo "cleaning..."
echo " "

rm -rf $DIROUT/$imgname.new.dat
echo "compession done!";
echo " "

