#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
cd scripts
clear

echo " "
echo "Input image/partition name :"
read
imgname=$REPLY

echo " "
echo "Converting sparse to raw image..."

./bin/simg2img $DIRIN/$imgname.img $DIROUT/$imgname.img >> log.txt
./bin/simg2img $DIRIN/$imgname.sparse.img $DIROUT/$imgname.img >> log.txt
rm -rf $DIRIN/*

echo " "
echo "Done! Output : $DIROUT"

