#!/bin/sh

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
dynamic_part_op_list=$DIROUT/dynamic_partitions_op_list
clear
cd scripts

input_size() {
	ODMSIZE=$(ls -nl $DIRIN/odm.img | awk '{print $5}')
	PRODUCTSIZE=$(ls -nl $DIRIN/product.img | awk '{print $5}')
	SYSTEMSIZE=$(ls -nl $DIRIN/system.img | awk '{print $5}')
	SYSEXTSIZE=$(ls -nl $DIRIN/system_ext.img | awk '{print $5}')
	VENDORSIZE=$(ls -nl $DIRIN/vendor.img | awk '{print $5}')
	SUPERSIZE=9124708352
}

a_dp_op_list() {
	if [ -f $dynamic_part_op_list ]; then
		rm -f $dynamic_part_op_list;
	fi;
	
	touch $DIROUT/dynamic_partitions_op_list
	echo "# Remove all existing dynamic partitions and groups before applying full OTA" >> $dynamic_part_op_list
	echo "remove_all_groups" >>  $dynamic_part_op_list
	echo "# Add group qti_dynamic_partitions with maximum size $SUPERSIZE" >>  $dynamic_part_op_list
	echo "add_group qti_dynamic_partitions $SUPERSIZE" >>  $dynamic_part_op_list
	echo "# Add partition system to group qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "add system qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "# Add partition vendor to group qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "add vendor qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "# Add partition product to group qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "add product qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "# Add partition odm to group qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "add odm qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "# Add partition system_ext to group qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "add system_ext qti_dynamic_partitions" >>  $dynamic_part_op_list
	echo "# Grow partition system from 0 to $SYSTEMSIZE" >>  $dynamic_part_op_list
	echo "resize system $SYSTEMSIZE" >>  $dynamic_part_op_list
	echo "# Grow partition vendor from 0 to $VENDORSIZE" >>  $dynamic_part_op_list
	echo "resize vendor $VENDORSIZE" >>  $dynamic_part_op_list
	echo "# Grow partition product from 0 to $PRODUCTSIZE" >>  $dynamic_part_op_list
	echo "resize product $PRODUCTSIZE" >>  $dynamic_part_op_list
	echo "# Grow partition odm from 0 to $ODMSIZE" >>  $dynamic_part_op_list
	echo "resize odm $ODMSIZE" >>  $dynamic_part_op_list
	echo "# Grow partition system_ext from 0 to $SYSEXTSIZE" >>  $dynamic_part_op_list
	echo "resize system_ext $SYSEXTSIZE" >>  $dynamic_part_op_list
}

ab_dp_op_list() {
	if [ -f $dynamic_part_op_list ]; then
		rm -f $dynamic_part_op_list;
	fi;
	
	touch $DIROUT/dynamic_partitions_op_list
	echo "# Remove all existing dynamic partitions and groups before applying full OTA" >> $dynamic_part_op_list
	echo "remove_all_groups" >> $dynamic_part_op_list
	echo "# Add group qti_dynamic_partitions_a with maximum size $SUPERSIZE" >> $dynamic_part_op_list
	echo "add_group qti_dynamic_partitions_a $SUPERSIZE" >> $dynamic_part_op_list
	echo "# Add group qti_dynamic_partitions_b with maximum size $SUPERSIZE" >> $dynamic_part_op_list
	echo "add_group qti_dynamic_partitions_b $SUPERSIZE" >> $dynamic_part_op_list
	echo "# Add partition system_a to group qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "add system_a qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "# Add partition system_b to group qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "add system_b qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "# Add partition system_ext_a to group qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "add system_ext_a qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "# Add partition system_ext_b to group qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "add system_ext_b qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "# Add partition product_a to group qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "add product_a qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "# Add partition product_b to group qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "add product_b qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "# Add partition vendor_a to group qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "add vendor_a qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "# Add partition vendor_b to group qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "add vendor_b qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "# Add partition odm_a to group qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "add odm_a qti_dynamic_partitions_a" >> $dynamic_part_op_list
	echo "# Add partition odm_b to group qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "add odm_b qti_dynamic_partitions_b" >> $dynamic_part_op_list
	echo "# Grow partition system_a from 0 to $SYSTEMSIZE" >> $dynamic_part_op_list
	echo "resize system_a $SYSTEMSIZE" >> $dynamic_part_op_list
	echo "# Grow partition system_ext_a from 0 to $SYSEXTSIZE" >> $dynamic_part_op_list
	echo "resize system_ext_a $SYSEXTSIZE" >> $dynamic_part_op_list
	echo "# Grow partition product_a from 0 to $PRODUCTSIZE" >> $dynamic_part_op_list
	echo "resize product_a $PRODUCTSIZE" >> $dynamic_part_op_list
	echo "# Grow partition vendor_a from 0 to $VENDORSIZE" >> $dynamic_part_op_list
	echo "resize vendor_a $VENDORSIZE" >> $dynamic_part_op_list
	echo "# Grow partition odm_a from 0 to $ODMSIZE" >> $dynamic_part_op_list
	echo "resize odm_a $ODMSIZE" >> $dynamic_part_op_list
}

brotli_lvl() {
	echo " "
	echo "Input Brotli compression level (0-11) :"
	read
	COMPLVL=$REPLY
	echo " "
	while true; do
   		read -p "Your preffered brotli compression level is $COMPLVL is that correct? (Y/N)" yn
    		case $yn in
			[Yy]* ) break;;
			[Nn]* ) exit;;
			* ) echo "Please answer yes or no.";;
		    esac
		done
}

compress() {

echo ""
echo "converting partitions into sparse"
img2simg $DIRIN/system.img $DIRIN/system.sparse.img
rm -rf $DIRIN/system.img
img2simg $DIRIN/vendor.img $DIRIN/vendor.sparse.img
rm -rf $DIRIN/vendor.img
img2simg $DIRIN/odm.img $DIRIN/odm.sparse.img
rm -rf $DIRIN/odm.img
img2simg $DIRIN/product.img $DIRIN/product.sparse.img
rm -rf $DIRIN/product.img
img2simg $DIRIN/system_ext.img $DIRIN/system_ext.sparse.img
rm -rf $DIRIN/system_ext.img

echo ""
echo "converting partitions into new.dat"

./bin/img2sdat.py $DIRIN/system.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/system.new.dat
mv $DIRIN/system.patch.dat $DIROUT/system.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/system.transfer.list
rm -rf $DIRIN/system.*

./bin/img2sdat.py $DIRIN/vendor.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/vendor.new.dat
mv $DIRIN/system.patch.dat $DIROUT/vendor.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/vendor.transfer.list
rm -rf $DIRIN/system.*
rm -rf $DIRIN/vendor.*

./bin/img2sdat.py $DIRIN/odm.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/odm.new.dat
mv $DIRIN/system.patch.dat $DIROUT/odm.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/odm.transfer.list
rm -rf $DIRIN/system.*
rm -rf $DIRIN/odm.*

./bin/img2sdat.py $DIRIN/product.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/product.new.dat
mv $DIRIN/system.patch.dat $DIROUT/product.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/product.transfer.list
rm -rf $DIRIN/system.*
rm -rf $DIRIN/product.*

./bin/img2sdat.py $DIRIN/system_ext.sparse.img -o $DIRIN/ -v 4
mv $DIRIN/system.new.dat $DIROUT/system_ext.new.dat
mv $DIRIN/system.patch.dat $DIROUT/system_ext.patch.dat
mv $DIRIN/system.transfer.list $DIROUT/system_ext.transfer.list
rm -rf $DIRIN/system.*
rm -rf $DIRIN/system_ext.*

echo " " 
echo "compressing system using brotli..."
brotli -q $COMPLVL $DIROUT/system.new.dat --output=$DIROUT/system.new.dat.br
rm -rf $DIROUT/system.new.dat
echo " " 
echo "compressing vendor using brotli..."
brotli -q $COMPLVL $DIROUT/vendor.new.dat --output=$DIROUT/vendor.new.dat.br
rm -rf $DIROUT/vendor.new.dat
echo " " 
echo "compressing odm using brotli..."
brotli -q $COMPLVL $DIROUT/odm.new.dat --output=$DIROUT/odm.new.dat.br
rm -rf $DIROUT/odm.new.dat
echo " " 
echo "compressing product using brotli..."
brotli -q $COMPLVL $DIROUT/product.new.dat --output=$DIROUT/product.new.dat.br
rm -rf $DIROUT/product.new.dat
echo " " 
echo "compressing system_ext using brotli..."
brotli -q $COMPLVL $DIROUT/system_ext.new.dat --output=$DIROUT/system_ext.new.dat.br
rm -rf $DIROUT/system_ext.new.dat

echo " "
echo "Done! Output : $DIROUT"

}

while true; do
    echo "Compiling for A only device or Virtual A/B?"
    echo "(1) A only"
    echo "(2) Virtual A/B "
    read -p "choose 1 or 2 : " choose
    case $choose in
        [1]* ) 
echo "Make sure to input your raw .img's to rom_input folder"
echo " "
echo "Compiling super with A only format"
echo " "

brotli_lvl
input_size
a_dp_op_list
compress
break;;


        [2]* ) 
echo "Make sure to input your raw .img's to rom_input folder"
echo " "
echo "Compiling super with Virtual A/B format"
echo " "

brotli_lvl
input_size
ab_dp_op_list
compress
break;;


        * ) echo "Please answer 1 or 2.";;
    esac
done
