#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
clear
cd scripts


echo " "
echo "Decompressing system using brotli..."
brotli -d $DIRIN/system.new.dat.br
rm -rf $DIRIN/system.new.dat.br
echo " "
echo "Decompressing vendor using brotli..."
brotli -d $DIRIN/vendor.new.dat.br
rm -rf $DIRIN/vendor.new.dat.br
echo " "
echo "Decompressing odm using brotli..."
brotli -d $DIRIN/odm.new.dat.br
rm -rf $DIRIN/odm.new.dat.br
echo " "
echo "Decompressing product using brotli..."
brotli -d $DIRIN/product.new.dat.br
rm -rf $DIRIN/product.new.dat.br
echo " "
echo "Decompressing system_ext using brotli..."
brotli -d $DIRIN/system_ext.new.dat.br
rm -rf $DIRIN/system_ext.new.dat.br

echo " "
echo "Converting system.new.dat to system.img (raw)"
./bin/sdat2img.py $DIRIN/system.transfer.list $DIRIN/system.new.dat $DIROUT/system.img
rm -rf $DIRIN/system.*
echo " "
echo "Converting vendor.new.dat to vendor.img (raw)"
./bin/sdat2img.py $DIRIN/vendor.transfer.list $DIRIN/vendor.new.dat $DIROUT/vendor.img
rm -rf $DIRIN/vendor.*
echo " "
echo "Converting odm.new.dat to odm.img (raw)"
./bin/sdat2img.py $DIRIN/odm.transfer.list $DIRIN/odm.new.dat $DIROUT/odm.img
rm -rf $DIRIN/odm.*
echo " "
echo "Converting productnew.dat to product.img (raw)"
./bin/sdat2img.py $DIRIN/product.transfer.list $DIRIN/product.new.dat $DIROUT/product.img
rm -rf $DIRIN/product.*
echo " "
echo "Converting system_ext.new.dat to system_ext.img (raw)"
./bin/sdat2img.py $DIRIN/system_ext.transfer.list $DIRIN/system_ext.new.dat $DIROUT/system_ext.img
rm -rf $DIRIN/system_ext.*

echo " "
echo "Done! Output : $DIROUT"
