#!/bin/bash

DIRTOOLS=$PWD
DIRIN=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
clear
cd scripts

datbr() {
    if [[ -f $DIRIN/$partition.new.dat.br ]]; then
	echo " "
	echo "Decompressing $partition using brotli..."
	brotli -d $DIRIN/$partition.new.dat.br
	rm -rf $DIRIN/$partition.new.dat.br
    else
    	echo " "
    	echo "there's no $partition.new.dat.br supplied! skipping..."
    fi
}

sdat2img() {
    if [[ -f $DIRIN/$partition.new.dat ]] && [[ -f $DIRIN/$partition.transfer.list ]]; then
	echo " "
	echo "Converting $partition.new.dat to $partition.img (raw)"
	./bin/sdat2img.py $DIRIN/$partition.transfer.list $DIRIN/$partition.new.dat $DIROUT/$partition.img >> log.txt
	rm -rf $DIRIN/$partition.*
    else
    	echo " "
    	echo "there's no $partition.new.dat and/or $partition.transfer.list supplied! skipping..."
    fi
}

echo " "
echo "========================================="

partition=system
datbr
partition=vendor
datbr
partition=odm
datbr
partition=product
datbr
partition=system_ext
datbr

echo " "
echo "========================================="

partition=system
sdat2img
partition=vendor
sdat2img
partition=odm
sdat2img
partition=product
sdat2img
partition=system_ext
sdat2img

echo " "
echo "========================================="
echo " "
echo "Done! Output : $DIROUT"
