#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) break;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Repack Splits (raw to dat.br)"
    echo "2. Unpack Splits"
    echo "3. Back to main menu"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/splits-compress

restart_tool;;

        2 ) 
   
bash $SCRIPTS/splits-decompress

restart_tool;;

        3 ) 

bash $DIRTOOLS/start;;


        * ) bash $SCRIPTS/splits-main;;
    esac
done


