#!/bin/sh
DIRTOOLS=$PWD
DIROUT=$DIRTOOLS/rom_output
ZIPNAME=$DIRTOOLS/split-partition.zip
clear

cd $DIROUT

zip $ZIPNAME dynamic_partitions_op_list system.* vendor.* odm.* product.* system_ext.*

cd $DIRTOOLS
