#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) break;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Repack Super"
    echo "2. Unpack Super (dat.br)"
    echo "3. Unpack Super (raw)"
    echo "4. Back to main menu"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/super-r

restart_tool;;

        2 ) 
   
bash $SCRIPTS/super-u-datbr

restart_tool;;

        3 ) 
   
bash $SCRIPTS/super-u-raw

restart_tool;;

	4 ) 
   
bash $DIRTOOLS/start;;


        * ) bash $SCRIPTS/super-main;;
    esac
done


