#!/bin/bash

DIRTOOLS=$PWD
DIRINPUT=$DIRTOOLS/rom_input
DIROUT=$DIRTOOLS/rom_output
DIRROM=$DIRTOOLS/ROM
clear
cd scripts

echo " "
echo " "
echo "Input Super image name :"
read
imgname=$REPLY

if [ -f $DIRINPUT/$imgname.new.dat.br ]; then

	echo " "
	echo "Decompressing brotli..."
	brotli -d $DIRINPUT/$imgname.new.dat.br
	rm -rf $DIRINPUT/$imgname.new.dat.br

	echo " "
	echo "Converting $imgname.new.dat to $imgname.img (raw)..."
	./bin/sdat2img.py $DIRINPUT/$imgname.transfer.list $DIRINPUT/$imgname.new.dat $DIROUT/$imgname.img >> log.txt
	rm -rf $DIRINPUT/$imgname.*

	echo " "
	echo "Unpacking $imgname.img..."
	./bin/lpunpack $DIROUT/$imgname.img $DIRROM/super >> log.txt
	rm -rf $DIROUT/$imgname.*

	echo " "
	echo "Done! Output : $DIRROM/super"

else

	echo "theres no image "$imgname.new.dat.br""
fi
