#!/bin/bash

USER=danda
DIRTOOLS=/home/$USER/Desktop
DIRINPUT=$DIRTOOLS/RomTools/rom_input
DIROUT=$DIRTOOLS/RomTools/rom_output
DIRROM=$DIRTOOLS/RomTools/ROM

echo " "
echo " "
echo "Input Super image name :"
read
imgname=$REPLY
echo " "
while true; do
    read -p "Your super image name is : $imgname is that correct? (Y/N)" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo " "


brotli -d $DIRINPUT/$imgname.new.dat.br
rm -rf $DIRINPUT/$imgname.new.dat.br

./bin/sdat2img.py $DIRINPUT/$imgname.transfer.list $DIRINPUT/$imgname.new.dat $DIROUT/$imgname.img
rm -rf $DIRINPUT/*

./bin/lpunpack $DIROUT/$imgname.img $DIRROM/super
rm -rf $DIROUT/*


