#!/bin/bash

DIRTOOLS=$PWD
DIRROM=$DIRTOOLS/ROM
clear
cd scripts

echo " "
echo "Unmounting partitions..."
echo " "
sudo umount $DIRROM/system >> log.txt
sudo umount $DIRROM/vendor >> log.txt
sudo umount $DIRROM/odm >> log.txt
sudo umount $DIRROM/product >> log.txt
sudo umount $DIRROM/system_ext >> log.txt

