#!/bin/sh
DIRTOOLS=$PWD
SCRIPTS=$DIRTOOLS/scripts

clear
cd $DIRTOOLS

restart_tool() {
echo " "
while true; do
   echo "start tools again? (y/n)"
   read -p "" yn
   case $yn in
        [Yy]* ) bash start;;
        [Nn]* ) exit;;   
        * ) echo "please choose yes or no";;
    esac
done
}

while true; do
    echo "========================="
    echo "   ROM TOOLS FOR LINUX   "
    echo "        by  Danda        "
    echo "========================="
    echo " "
    echo "1. Umount raw image and resize to smallest size"
    echo "2. Umount raw image and resize with free space "
    echo "3. Umount without resizing"
    echo "4. Back to main menu"
    
    read -p "" choose
    case $choose in
    
        1 ) 

bash $SCRIPTS/umount-resize

restart_tool;;

        2 ) 

bash $SCRIPTS/umount-resize-freespace

restart_tool;;

        3 ) 
   
bash $SCRIPTS/umount-normal

restart_tool;;

        4 ) 

bash $DIRTOOLS/start;;


        * ) bash $SCRIPTS/umount-main;;
    esac
done


