#!/bin/bash

cd ..
DIRTOOLS=$PWD
cd scripts
DIRROM=$DIRTOOLS/ROM

sudo umount $DIRROM/system
sudo umount $DIRROM/vendor
sudo umount $DIRROM/odm
sudo umount $DIRROM/product
sudo umount $DIRROM/system_ext

