#!/bin/bash

DIRTOOLS=$PWD
DIRROM=$DIRTOOLS/ROM
clear
cd scripts

resize_to_build(){
	if [ -f $DIRROM/$valset.img ]; then
		e2fsck -yf $DIRROM/$valset.img >> log.txt
		resize2fs -M $DIRROM/$valset.img >> log.txt
		e2fsck -yf $DIRROM/$valset.img >> log.txt
		
		if [[ $valset == "system" ]] || [[ $valset == "system_a" ]] || [[ $valset == *"vendor"* ]]; then
			vsizenow=$(ls -nl $DIRROM/$valset.img | awk '{print $5}')
			sizeimg=$((($vsizenow + 100000000)/1000))K
			resize2fs $DIRROM/$valset.img $sizeimg
			e2fsck -yf $DIRROM/$valset.img
		fi;
	fi;
}

echo " "
echo "Unmounting partitions..."
echo " "
sudo umount $DIRROM/system >> log.txt
sudo umount $DIRROM/vendor >> log.txt
sudo umount $DIRROM/odm >> log.txt
sudo umount $DIRROM/product >> log.txt
sudo umount $DIRROM/system_ext >> log.txt

echo "Resizing partitions..."
echo " "
# Resize image to minimum
valset=system
resize_to_build
valset=system_ext
resize_to_build
valset=vendor
resize_to_build
valset=odm
resize_to_build
valset=product
resize_to_build
